import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:vroom_app/models/car_model.dart'; // Import your Car model

class MockDataService {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  // Function to add mock car data to Firestore
  Future<void> addMockCars() async {
    // Define mock car data with lister information
    final mockCar1 = Car(
      id: '', // ID will be generated by Firestore
      make: 'Toyota',
      model: 'Camry',
      year: 2015,
      pricePerDay: 1500.00,
      imageUrl: 'assets/images/car1.jpeg', // Changed to local asset path
      fuelType: 'Petrol',
      seats: 5,
      isAvailable: true,
      listerName: 'City Car Rentals',
      listerPhone: '+2547-111-2222',
      listerEmail: 'info@citycarrentals.com',
    );
    final mockCar2 = Car(
      id: '',
      make: 'Honda',
      model: 'Civic',
      year: 2020,
      pricePerDay: 4500.00,
      imageUrl: 'assets/images/car2.jpeg', // Changed to local asset path
      fuelType: 'Electric',
      seats: 4,
      isAvailable: false,
      listerName: 'Green Wheels Co.',
      listerPhone: '+2547-333-4444',
      listerEmail: 'contact@greenwheels.com',
    );
    final mockCar3 = Car(
      id: '',
      make: 'Mercedes-Benz',
      model: 'C-Class',
      year: 2023,
      pricePerDay: 12000.00,
      imageUrl: 'assets/images/car3.jpeg', // Changed to local asset path
      fuelType: 'petrol',
      seats: 5,
      isAvailable: true,
      listerName: 'Luxury Drives Inc.',
      listerPhone: '+2547-555-6666',
      listerEmail: 'sales@luxurydrives.com',
    );

    try {
      // Add the mock car data to the 'cars' collection
      // You might want to delete existing cars in Firestore before running this
      // to ensure only these new mock cars with local asset paths are present.
      // (This would require a separate function to delete all cars)
      await _firestore.collection('cars').add(mockCar1.toFirestore());
      await _firestore.collection('cars').add(mockCar2.toFirestore());
      await _firestore.collection('cars').add(mockCar3.toFirestore());
      print('Mock cars with local asset paths added successfully to Firestore!');
    } catch (e) {
      print('Failed to add mock cars to Firestore: $e');
    }
  }
}
