// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR0dJxKqnaOafpsyBNTd7uT7-Ju7RKFYc',
    appId: '1:145988561319:web:3f513d668d19e084ed2e82',
    messagingSenderId: '145988561319',
    projectId: 'vroom-car-hire-app',
    authDomain: 'vroom-car-hire-app.firebaseapp.com',
    storageBucket: 'vroom-car-hire-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMdJP_pBClQ4D7FO94Baa-57kF9ixVGyg',
    appId: '1:145988561319:android:405a04a1431c3c1fed2e82',
    messagingSenderId: '145988561319',
    projectId: 'vroom-car-hire-app',
    storageBucket: 'vroom-car-hire-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf00wOtPy0Ps5lDGuSYKpjlVgIxa6aZfU',
    appId: '1:145988561319:ios:c0142ad58267a925ed2e82',
    messagingSenderId: '145988561319',
    projectId: 'vroom-car-hire-app',
    storageBucket: 'vroom-car-hire-app.firebasestorage.app',
    iosBundleId: 'com.example.vroomApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf00wOtPy0Ps5lDGuSYKpjlVgIxa6aZfU',
    appId: '1:145988561319:ios:c0142ad58267a925ed2e82',
    messagingSenderId: '145988561319',
    projectId: 'vroom-car-hire-app',
    storageBucket: 'vroom-car-hire-app.firebasestorage.app',
    iosBundleId: 'com.example.vroomApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR0dJxKqnaOafpsyBNTd7uT7-Ju7RKFYc',
    appId: '1:145988561319:web:640c73091cd37f10ed2e82',
    messagingSenderId: '145988561319',
    projectId: 'vroom-car-hire-app',
    authDomain: 'vroom-car-hire-app.firebaseapp.com',
    storageBucket: 'vroom-car-hire-app.firebasestorage.app',
  );
}
